spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa_practice
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
#      show-sql: true
      format_sql: true
loging.level:
  org.hibernate.SQL: debug