spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa_practice
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
loging.level:
  org.hibernate.SQL: debug